export const TIMEZONES = [
    { value: 'utc-12', label: 'UTC−12:00' },
    { value: 'utc-11', label: 'UTC−11:00' },
    { value: 'utc-10', label: 'UTC−10:00 — Гавайи' },
    { value: 'utc-9', label: 'UTC−09:00 — Аляска' },
    { value: 'utc-8', label: 'UTC−08:00 — Лос-Анджелес' },
    { value: 'utc-7', label: 'UTC−07:00 — Денвер' },
    { value: 'utc-6', label: 'UTC−06:00 — Чикаго' },
    { value: 'utc-5', label: 'UTC−05:00 — Нью-Йорк' },
    { value: 'utc-4', label: 'UTC−04:00 — Сантьяго' },
    { value: 'utc-3', label: 'UTC−03:00 — Буэнос-Айрес' },
    { value: 'utc-2', label: 'UTC−02:00' },
    { value: 'utc-1', label: 'UTC−01:00 — Азорские о-ва' },
    { value: 'utc+0', label: 'UTC±00:00 — Лондон' },
    { value: 'utc+1', label: 'UTC+01:00 — Берлин, Париж' },
    { value: 'utc+2', label: 'UTC+02:00 — Киев, Хельсинки' },
    { value: 'utc+3', label: 'UTC+03:00 — Москва' },
    { value: 'utc+3.5', label: 'UTC+03:30 — Тегеран' },
    { value: 'utc+4', label: 'UTC+04:00 — Дубай' },
    { value: 'utc+4.5', label: 'UTC+04:30 — Кабул' },
    { value: 'utc+5', label: 'UTC+05:00 — Ташкент' },
    { value: 'utc+5.5', label: 'UTC+05:30 — Мумбаи' },
    { value: 'utc+5.75', label: 'UTC+05:45 — Катманду' },
    { value: 'utc+6', label: 'UTC+06:00 — Алматы' },
    { value: 'utc+6.5', label: 'UTC+06:30 — Янгон' },
    { value: 'utc+7', label: 'UTC+07:00 — Бангкок' },
    { value: 'utc+8', label: 'UTC+08:00 — Пекин, Сингапур' },
    { value: 'utc+9', label: 'UTC+09:00 — Токио' },
    { value: 'utc+9.5', label: 'UTC+09:30 — Аделаида' },
    { value: 'utc+10', label: 'UTC+10:00 — Сидней' },
    { value: 'utc+11', label: 'UTC+11:00 — Магадан' },
    { value: 'utc+12', label: 'UTC+12:00 — Окленд' },
    { value: 'utc+13', label: 'UTC+13:00 — Самоа' },
    { value: 'utc+14', label: 'UTC+14:00 — Киритимати' },
];
